[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dao_voting = "8twZTybaCyudgUKJPEkdgD9SkFfoABrUsx86gwKgnv8h"

[programs.devnet]
dao_voting = "8twZTybaCyudgUKJPEkdgD9SkFfoABrUsx86gwKgnv8h"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
wallet = "~/my-keypair.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
